### ISSUE TITLE
New command 

### ISSUE THREAD

**Issue by Pradeep5986** [fifa-mobile/discord-bot#11]
Add one more command like($heros)in hero section of bot,by this command ppl can see all heros that we are having.
We have ($hero) list command that only show heros that ppl have not all heros

**Comment by juve938383** [comment]
$hero catalogue or something🤣

**Comment by Pradeep5986** [comment]
Edited😅

**Comment by yuulye** [comment]
I think I'll make $heroes, the plural of hero is heroes isn't it?

**Comment by Pradeep5986** [comment]
Do it ,my bad english 😅

**Comment by juve938383** [comment]
Thanks again yuulye!!
