### ISSUE TITLE
New hero

### ISSUE THREAD

**Issue by Pradeep5986** [fifa-mobile/discord-bot#12]
Add new heros-
1:Superman(CW)
![Screenshot_20200807-214454_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666251-a2ea3080-d8f7-11ea-81bc-3180a556aa20.jpg)
2:Ben10![Screenshot_20200807-213936_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666291-b8f7f100-d8f7-11ea-8298-8129e249e55a.jpg)
3:Yoda![Screenshot_20200807-212544_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666325-c9a86700-d8f7-11ea-99db-27102d2ed64c.jpg)
4:Darth Vader![Screenshot_20200807-212517_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666386-e8a6f900-d8f7-11ea-8647-719611bd4338.jpg)
5:Darth Sidious![Screenshot_20200807-212352_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666473-0f652f80-d8f8-11ea-82af-5db814068585.jpg)
6:Kylo Ren![Screenshot_20200807-212216_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666548-2f94ee80-d8f8-11ea-9a0a-83a667942df0.jpg)
7:Anakin Skywalker ![Screenshot_20200807-212053_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666599-43405500-d8f8-11ea-8865-d09d1db1bfa5.jpg)
8:Luke Skywalker (Dark Empire)![Screenshot_20200807-211936_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666679-6965f500-d8f8-11ea-8a41-0ee7a009f503.jpg)
9:Mera(DCEU)![Screenshot_20200807-211809_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666744-8c90a480-d8f8-11ea-93b7-dcdce5ccff7d.jpg)
10:Flash(CW)![Screenshot_20200807-211739_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666813-a29e6500-d8f8-11ea-9adc-e839d17b2a15.jpg)
11:Aquaman (DCEU)![Screenshot_20200807-211637_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666876-c1046080-d8f8-11ea-986b-c75409566eda.jpg)
12:Wonder Woman ![Screenshot_20200807-211358_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666918-d4173080-d8f8-11ea-98d9-209d751c7dc4.jpg)
13:Batman![Screenshot_20200807-211244_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89666954-e3967980-d8f8-11ea-8185-bcf2be52a0b5.jpg)
14:Batman(Gotham by Gaslight)![Screenshot_20200807-204408_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89667052-0f196400-d8f9-11ea-89aa-c5e1e53ccba4.jpg)
15:Gotham Girl![Screenshot_20200807-204319_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89667084-23f5f780-d8f9-11ea-9b52-cd83a43f7b0f.jpg)
16:Gotham![Screenshot_20200807-204251_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89667114-33754080-d8f9-11ea-97ae-6f5888cac552.jpg)

**Comment by juve938383** [comment]
Pradeep Hroically doing this so guess we can close the issue.
