### ISSUE TITLE
$announce new lines

### ISSUE THREAD

**Issue by juve938383** [fifa-mobile/discord-bot#20]
When I use $announce and use the Enter button in my message to get in a new line the bot doesn't include it.
Example:
**Input:**
$announce Hi
Abc
A
**Output:**
![Screenshot_20200812-201930_Discord](https://user-images.githubusercontent.com/58861443/90052242-27162c80-dcd9-11ea-9f27-d545a057a412.jpg)

**Comment by yuulye** [comment]
Ability to attach image also

**Comment by juve938383** [comment]
Well, we can send an image only message by sending link but we can't do it by sending both text and image link.

**Comment by juve938383** [comment]
Thanks a lot yuul!
