### ISSUE TITLE
Front Page

### ISSUE THREAD

**Issue by yuulye** [fifa-mobile/discord-bot#27]
Design and implement page using dynamic view
https://ahqleague.herokuapp.com

**Comment by juve938383** [comment]
Want to make it look good?

**Comment by yuulye** [comment]
The current page is for my personal links, thinking of making changes for more of organization looks, just a quick page, and implement the dynamic view, after that you guys can design it with whatever you want, I am gonna move to market page.

**Comment by juve938383** [comment]
Nice.We can add a button link to market page here.Btw, I have read your blog,it's pretty neat

🏃‍♂️

**Comment by yuulye** [comment]
checkout https://ahqleague.herokuapp.com/ although it is a very basic page and doesn't handle mobile view.
take a look at https://www.w3schools.com/html/html_responsive.asp how to implement responsive design
