### ISSUE TITLE
$market output nothing

### ISSUE THREAD

**Issue by yuulye** [fifa-mobile/discord-bot#3]
maybe it's better to remove $market price and change it with only $market
![Screenshot from 2020-08-06 13-12-13](https://user-images.githubusercontent.com/34153114/89497440-92966080-d7e6-11ea-8219-fa5ffa92f9ec.png)

**Comment by juve938383** [comment]
Done

**Comment by yuulye** [comment]
Hahaha, what an elegant solution 😂👍

**Comment by juve938383** [comment]
You know I am nub🤣🤣

**Comment by yuulye** [comment]
I really thought to remove the `price(s)` options but this is much better, cleaner, clever and effortless (effort to think about it maybe 😂)
