### ISSUE TITLE
Show players when buying from the market

### ISSUE THREAD

**Issue by yuulye** [fifa-mobile/discord-bot#4]

**Comment by yuulye** [comment]
@juve938383 as we know there are only a few cards for type (prime, icon, master, etc.) If the command executed `$market buy 1 10` let's say there are only 5 cards available then how can I prevent duplicated pull?

How about we can only buy one at a time and disable the current `amount` option?

**Comment by John-caleb** [comment]
@yuulye I don't see any problem if there's a duplicated pull
But , if there are limited cards , maybe you can set a limit to the amount bought

**Comment by yuulye** [comment]
> @yuulye I don't see any problem if there's a duplicated pull
> But , if there are limited cards , maybe you can set a limit to the amount bought

That's actually an excellent idea! You're now officially a contributor!

**Comment by juve938383** [comment]
Why complicate it pronubs?My plan is to show the player only when user buys 1 of the kind.It would be complicated showing players for multiple players and setting a limit may not be that good for a fearure I've pmanned.Just showing it for one player purchases seems reasonable to me.

**Comment by yuulye** [comment]
Hahaha, okay guys, I think I'll go with one time buy only for the beginning, we can discuss more after the implementation

**Comment by juve938383** [comment]
I can add it later today.

**Comment by yuulye** [comment]
I'll assign the issue to you then

**Comment by juve938383** [comment]
Thanks a lot yuulye!😃

**Comment by yuulye** [comment]
Hahaha I just tidying your code a little bit
