### ISSUE TITLE
Image asset placement

### ISSUE THREAD

**Issue by yuulye** [fifa-mobile/discord-bot#5]
instead of placing currency_Item_COIN.png inside commands folder, it's cleaner to place it inside images folder
![image-asset](https://user-images.githubusercontent.com/34153114/89557264-bedccc00-d83c-11ea-9b83-1d297af8e42b.png)
![image](https://user-images.githubusercontent.com/34153114/89557299-c7cd9d80-d83c-11ea-8aee-f7f7507561e2.png)

**Comment by Pradeep5986** [comment]
Why not adding one more option that is of auction of players

**Comment by juve938383** [comment]
Done
