### ISSUE TITLE
New hero

### ISSUE THREAD

**Issue by Pradeep5986** [fifa-mobile/discord-bot#6]
Add new hero Kaguya Ōtsutsuki

Ōtsutsuki Kaguya

![Screenshot_20200806-233659_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89566471-d9fc0b80-d83d-11ea-87cb-e9cd2d6b79e5.jpg)![Screenshot_20200806-233645_Chrome.jpg](https://user-images.githubusercontent.com/68916509/89566480-dc5e6580-d83d-11ea-9798-0a0c4707a5b0.jpg)

**Comment by juve938383** [comment]
Same as other hero topic
